formatter: "markdown" # this is required

version: ""

header-from: "main.tf"
footer-from: ""

#recursive:
#  enabled: true
#  path: modules

sections:
  #  hide: [ ]
  show:
    - data-sources
    - header
    - footer
    - inputs
    - outputs
    - modules
    - providers
    - requirements
    - resources

content: |-
  {{ .Header }}
  # Опис ресурсів Terraform
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Footer }}



output:
  file: "Readme.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: false
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 0
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
