---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: prod-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: grpc
      port: 9555
      protocol: TCP
      targetPort: 9556
  selector:
    app: adservice
    project: microservices-demo
    stage: prod
  sessionAffinity: None
  type: ClusterIP