---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: stage-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: web
      port: 7070
      protocol: TCP
      targetPort: 7070
  selector:
    app: cartservice
    project: microservices-demo
    stage: stage
  sessionAffinity: None
  type: ClusterIP