---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: prod-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: grpc
      port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    app: checkoutservice
    project: microservices-demo
    stage: prod
  sessionAffinity: None
  type: ClusterIP