---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: prod-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: grpc
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: currencyservice
    project: microservices-demo
    stage: prod
  sessionAffinity: None
  type: ClusterIP