---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-currencyservice
  namespace: stage-microservices-demo
  labels:
    deployment_name: stage-currencyservice
    app.kubernetes.io/name: currencyservice
    app.kubernetes.io/version: "0.1.0"
    project_name: microservices-demo
    namespace_name: stage-microservices-demo
    app.kubernetes.io/created-by: developer_company.com
    app.kubernetes.io/managed-by: devops_company.com
    environment_stage: stage
    environment_uri: stage-env.company.com
    app.kubernetes.io/component: advertise-service
    business_domain: sales
    business_owner: marketing_company.com
    app.kubernetes.io/instance: baremetal-rancher

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: stage-currencyservice
      namespace: stage-microservices-demo
      labels:
        deployment_name: stage-currencyservice
        deployment_app: currencyservice
        app.kubernetes.io/name: currencyservice
        app.kubernetes.io/version: "0.1.0"
        project_name: microservices-demo
        namespace_name: stage-microservices-demo
    spec:
      containers:
        - name: stage-currencyservice
          image: registry.gitlab.com/devops1121/microservices-demo-google/currencyservice:stage
          imagePullPolicy: Always
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1000m
          ports:
            - containerPort: 7000
              protocol: TCP
              name: grpc
          env:
          - name: PORT
            value: "7000"
          - name: "DISABLE_TRACING"
            value: "1"
          - name: "DISABLE_PROFILER"
            value: "1"
          - name: "DISABLE_DEBUGGER"
            value: "1"
 
      restartPolicy: Always
      imagePullSecrets:
        - name: registry.gitlab
  selector:
    matchLabels:
      deployment_app: currencyservice
      namespace_name: stage-microservices-demo
      environment_stage: stage


