---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
    project: microservices-demo
    stage: prod
  sessionAffinity: None
  type: ClusterIP