---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: prod-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: paymentservice
    project: microservices-demo
    stage: prod
  sessionAffinity: None
  type: ClusterIP