---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: stage-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: grpc
      port: 3550
      protocol: TCP
      targetPort: 3550
  selector:
    app: productcatalogservice
    project: microservices-demo
    stage: stage
  sessionAffinity: None
  type: ClusterIP