---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: stage-microservices-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: recommendationservice
    project: microservices-demo
    stage: stage
  sessionAffinity: None
  type: ClusterIP