include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.checkoutservice_auto_rules:
  rules:
    - changes:
        - src/checkoutservice/**/**/*
      when: always

.checkoutservice_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /checkoutservice-manual/"
      when: always

auto_checkoutservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/checkoutservice/
    IMAGE_NAME: checkoutservice
  extends:
    - .checkoutservice_auto_rules
    - .build_image

manual_checkoutservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/checkoutservice/
    IMAGE_NAME: checkoutservice
  extends:
    - .checkoutservice_manual_rules
    - .build_image

pull_auto_checkoutservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: checkoutservice
  extends:
    - .checkoutservice_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_checkoutservice_debug
      optional: true

pull_manual_checkoutservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: checkoutservice
  extends:
    - .checkoutservice_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_checkoutservice_debug
      optional: true

push_checkoutservice_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: checkoutservice
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".checkoutservice_auto_rules", "rules" ]
    - !reference [ ".checkoutservice_manual_rules", "rules" ]
  needs:
    - job: pull_manual_checkoutservice_sha
      optional: true
    - job: pull_auto_checkoutservice_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: checkoutservice
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/checkoutservice checkoutservice=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_checkoutservice_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_checkoutservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/checkoutservice-stage-deployment.yaml
    - kubectl apply -f kubernetes/checkoutservice-stage-service.yaml
  rules:
    - changes:
        - kubernetes/checkoutservice-stage-deployment.yaml
        - kubernetes/checkoutservice-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_checkoutservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/checkoutservice-prod-deployment.yaml
    - kubectl apply -f kubernetes/checkoutservice-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual