include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.currencyservice_auto_rules:
  rules:
    - changes:
        - src/currencyservice/**/**/*
      when: always

.currencyservice_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /currencyservice-manual/"
      when: always

auto_currencyservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/currencyservice/
    IMAGE_NAME: currencyservice
  extends:
    - .currencyservice_auto_rules
    - .build_image

manual_currencyservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/currencyservice/
    IMAGE_NAME: currencyservice
  extends:
    - .currencyservice_manual_rules
    - .build_image

pull_auto_currencyservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: currencyservice
  extends:
    - .currencyservice_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_currencyservice_debug
      optional: true

pull_manual_currencyservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: currencyservice
  extends:
    - .currencyservice_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_currencyservice_debug
      optional: true

push_currencyservice_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: currencyservice
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".currencyservice_auto_rules", "rules" ]
    - !reference [ ".currencyservice_manual_rules", "rules" ]
  needs:
    - job: pull_manual_currencyservice_sha
      optional: true
    - job: pull_auto_currencyservice_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: currencyservice
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/currencyservice currencyservice=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_currencyservice_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_currencyservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/currencyservice-stage-deployment.yaml
    - kubectl apply -f kubernetes/currencyservice-stage-service.yaml
  rules:
    - changes:
        - kubernetes/currencyservice-stage-deployment.yaml
        - kubernetes/currencyservice-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_currencyservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/currencyservice-prod-deployment.yaml
    - kubectl apply -f kubernetes/currencyservice-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual