include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.cartservice_auto_rules:
  rules:
    - changes:
        - src/cartservice/**/**/*
      when: always

.cartservice_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /cartservice-manual/"
      when: always

auto_cartservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/cartservice/
    IMAGE_NAME: cartservice
  extends:
    - .cartservice_auto_rules
    - .build_image

manual_cartservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/cartservice/
    IMAGE_NAME: cartservice
  extends:
    - .cartservice_manual_rules
    - .build_image

pull_auto_cartservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: cartservice
  extends:
    - .cartservice_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_cartservice_debug
      optional: true

pull_manual_cartservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: cartservice
  extends:
    - .cartservice_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_cartservice_debug
      optional: true

push_cartservice_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: cartservice
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".cartservice_auto_rules", "rules" ]
    - !reference [ ".cartservice_manual_rules", "rules" ]
  needs:
    - job: pull_manual_cartservice_sha
      optional: true
    - job: pull_auto_cartservice_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: cartservice
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/cartservice cartservice=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_cartservice_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_cartservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/cartservice-stage-deployment.yaml
    - kubectl apply -f kubernetes/cartservice-stage-service.yaml
  rules:
    - changes:
        - kubernetes/cartservice-stage-deployment.yaml
        - kubernetes/cartservice-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_cartservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/cartservice-prod-deployment.yaml
    - kubectl apply -f kubernetes/cartservice-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual