include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.frontend_auto_rules:
  rules:
    - changes:
        - src/frontend/**/**/*
      when: always

.frontend_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /frontend-manual/"
      when: always

auto_frontend_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/frontend/
    IMAGE_NAME: frontend
  extends:
    - .frontend_auto_rules
    - .build_image

manual_frontend_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/frontend/
    IMAGE_NAME: frontend
  extends:
    - .frontend_manual_rules
    - .build_image

pull_auto_frontend_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: frontend
  extends:
    - .frontend_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_frontend_debug
      optional: true

pull_manual_frontend_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: frontend
  extends:
    - .frontend_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_frontend_debug
      optional: true

push_frontend_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: frontend
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".frontend_auto_rules", "rules" ]
    - !reference [ ".frontend_manual_rules", "rules" ]
  needs:
    - job: pull_manual_frontend_sha
      optional: true
    - job: pull_auto_frontend_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: frontend
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/frontend frontend=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_frontend_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_frontend:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/frontend-stage-deployment.yaml
    - kubectl apply -f kubernetes/frontend-stage-service.yaml
  rules:
    - changes:
        - kubernetes/frontend-stage-deployment.yaml
        - kubernetes/frontend-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_frontend:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/frontend-prod-deployment.yaml
    - kubectl apply -f kubernetes/frontend-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual