include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.loadgenerator_auto_rules:
  rules:
    - changes:
        - src/loadgenerator/**/**/*
      when: always

.loadgenerator_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /loadgenerator-manual/"
      when: always

auto_loadgenerator_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/loadgenerator/
    IMAGE_NAME: loadgenerator
  extends:
    - .loadgenerator_auto_rules
    - .build_image

manual_loadgenerator_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/loadgenerator/
    IMAGE_NAME: loadgenerator
  extends:
    - .loadgenerator_manual_rules
    - .build_image

pull_auto_loadgenerator_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: loadgenerator
  extends:
    - .loadgenerator_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_loadgenerator_debug
      optional: true

pull_manual_loadgenerator_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: loadgenerator
  extends:
    - .loadgenerator_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_loadgenerator_debug
      optional: true

push_loadgenerator_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: loadgenerator
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".loadgenerator_auto_rules", "rules" ]
    - !reference [ ".loadgenerator_manual_rules", "rules" ]
  needs:
    - job: pull_manual_loadgenerator_sha
      optional: true
    - job: pull_auto_loadgenerator_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: loadgenerator
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/loadgenerator loadgenerator=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_loadgenerator_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_loadgenerator:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/loadgenerator-stage-deployment.yaml
    - kubectl apply -f kubernetes/loadgenerator-stage-service.yaml
  rules:
    - changes:
        - kubernetes/loadgenerator-stage-deployment.yaml
        - kubernetes/loadgenerator-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_loadgenerator:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/loadgenerator-prod-deployment.yaml
    - kubectl apply -f kubernetes/loadgenerator-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual