include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.paymentservice_auto_rules:
  rules:
    - changes:
        - src/paymentservice/**/**/*
      when: always

.paymentservice_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /paymentservice-manual/"
      when: always

auto_paymentservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/paymentservice/
    IMAGE_NAME: paymentservice
  extends:
    - .paymentservice_auto_rules
    - .build_image

manual_paymentservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/paymentservice/
    IMAGE_NAME: paymentservice
  extends:
    - .paymentservice_manual_rules
    - .build_image

pull_auto_paymentservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: paymentservice
  extends:
    - .paymentservice_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_paymentservice_debug
      optional: true

pull_manual_paymentservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: paymentservice
  extends:
    - .paymentservice_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_paymentservice_debug
      optional: true

push_paymentservice_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: paymentservice
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".paymentservice_auto_rules", "rules" ]
    - !reference [ ".paymentservice_manual_rules", "rules" ]
  needs:
    - job: pull_manual_paymentservice_sha
      optional: true
    - job: pull_auto_paymentservice_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: paymentservice
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/paymentservice paymentservice=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_paymentservice_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_paymentservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/paymentservice-stage-deployment.yaml
    - kubectl apply -f kubernetes/paymentservice-stage-service.yaml
  rules:
    - changes:
        - kubernetes/paymentservice-stage-deployment.yaml
        - kubernetes/paymentservice-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_paymentservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/paymentservice-prod-deployment.yaml
    - kubectl apply -f kubernetes/paymentservice-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual