include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.productcatalogservice_auto_rules:
  rules:
    - changes:
        - src/productcatalogservice/**/**/*
      when: always

.productcatalogservice_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /productcatalogservice-manual/"
      when: always

auto_productcatalogservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/productcatalogservice/
    IMAGE_NAME: productcatalogservice
  extends:
    - .productcatalogservice_auto_rules
    - .build_image

manual_productcatalogservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/productcatalogservice/
    IMAGE_NAME: productcatalogservice
  extends:
    - .productcatalogservice_manual_rules
    - .build_image

pull_auto_productcatalogservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: productcatalogservice
  extends:
    - .productcatalogservice_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_productcatalogservice_debug
      optional: true

pull_manual_productcatalogservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: productcatalogservice
  extends:
    - .productcatalogservice_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_productcatalogservice_debug
      optional: true

push_productcatalogservice_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: productcatalogservice
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".productcatalogservice_auto_rules", "rules" ]
    - !reference [ ".productcatalogservice_manual_rules", "rules" ]
  needs:
    - job: pull_manual_productcatalogservice_sha
      optional: true
    - job: pull_auto_productcatalogservice_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: productcatalogservice
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/productcatalogservice productcatalogservice=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_productcatalogservice_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_productcatalogservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/productcatalogservice-stage-deployment.yaml
    - kubectl apply -f kubernetes/productcatalogservice-stage-service.yaml
  rules:
    - changes:
        - kubernetes/productcatalogservice-stage-deployment.yaml
        - kubernetes/productcatalogservice-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_productcatalogservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/productcatalogservice-prod-deployment.yaml
    - kubectl apply -f kubernetes/productcatalogservice-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual