include:
  - project: "devops1121/microservices-demo-google"
    ref: "ci-template"
    file:
      - ci/ci_docker_build.yml
      - ci/ci_variables.yml
      - ci/kubectl_handler.yml

variables: &global_var
  extends: .global_vars

stages:
  - build-debug-image
  - pull-debug
  - push-image
  - deploy

.recommendationservice_auto_rules:
  rules:
    - changes:
        - src/recommendationservice/**/**/*
      when: always

.recommendationservice_manual_rules:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /recommendationservice-manual/"
      when: always

auto_recommendationservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/recommendationservice/
    IMAGE_NAME: recommendationservice
  extends:
    - .recommendationservice_auto_rules
    - .build_image

manual_recommendationservice_debug:
  stage: build-debug-image
  variables:
    <<: *global_var
    BUILD_CONTEXT: /src/recommendationservice/
    IMAGE_NAME: recommendationservice
  extends:
    - .recommendationservice_manual_rules
    - .build_image

pull_auto_recommendationservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: recommendationservice
  extends:
    - .recommendationservice_auto_rules
    - .pull_debug_commit_sha
  needs:
    - job: auto_recommendationservice_debug
      optional: true

pull_manual_recommendationservice_sha:
  stage: pull-debug
  variables:
    <<: *global_var
    IMAGE_NAME: recommendationservice
  extends:
    - .recommendationservice_manual_rules
    - .pull_debug_commit_sha
  needs:
    - job: manual_recommendationservice_debug
      optional: true

push_recommendationservice_image:
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: recommendationservice
  extends:
    - .deploy_latest_tag_to_registry
    - .deploy_branch_tag_to_registry
  rules:
    - !reference [ ".recommendationservice_auto_rules", "rules" ]
    - !reference [ ".recommendationservice_manual_rules", "rules" ]
  needs:
    - job: pull_manual_recommendationservice_sha
      optional: true
    - job: pull_auto_recommendationservice_sha
      optional: true

manual_deploy_latest_image:
  before_script:
    - ""
  stage: push-image
  variables:
    <<: *global_var
    IMAGE_NAME: recommendationservice
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - 'kubectl set image deployment/recommendationservice recommendationservice=$DEV_TAG'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  needs:
    - job: push_recommendationservice_image
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  when: manual

auto_deploy_stage_recommendationservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/recommendationservice-stage-deployment.yaml
    - kubectl apply -f kubernetes/recommendationservice-stage-service.yaml
  rules:
    - changes:
        - kubernetes/recommendationservice-stage-deployment.yaml
        - kubernetes/recommendationservice-stage-service.yaml
      when: always
    - if: '$CI_COMMIT_BRANCH == "stage"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com

manual_deploy_production_recommendationservice:
  before_script:
    - ""
  stage: deploy
  variables:
    <<: *global_var
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ "" ]
  extends:
    - .kubectl-handler
  script:
    - kubectl apply -f kubernetes/recommendationservice-prod-deployment.yaml
    - kubectl apply -f kubernetes/recommendationservice-prod-service.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: stage
    url: http://stage-cluster.dvpslabs.com
  when: manual