---
# @action ./tasks/ubuntu20/hosts.yml # Призначає ноді необхідний `hostname` та генерує коректний файл `/etc/hosts`, в якому вказані всі ноди с їх IP-адресами та `hostname`. Для цього використовується шаблон з `/templates/hosts.j2`
- name: Set nodes hostnames
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Generate /etc/hosts file for all nodes
  ansible.builtin.template:
    dest: /etc/hosts
    src: ../../templates/hosts.j2
    force: yes
    mode: '06444'
    owner: 'root'
    group: 'root'
