name: Push Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f mcsvc/docker-compose.yml build
          docker-compose -f mcsvc/docker-compose.yml push

      - name: Deploy services
        run: |
          docker-compose -f mcsvc/docker-compose.yml up -d

      - name: Clean up
        if: always()
        run: |
          docker-compose -f mcsvc/docker-compose.yml down
