name: Deploy Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push adservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/adservice:2.1

    - name: Build and push cartservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/cartservice:2.1

    - name: Build and push checkoutservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/checkoutservice:2.1

    - name: Build and push currencyservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/currencyservice:2.1

    - name: Build and push emailservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/emailservice:2.1

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/frontend:2.0

    - name: Build and push loadgenerator
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/loadgenerator:2.1

    - name: Build and push paymentservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/paymentservice:2.1

    - name: Build and push recommendationservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/recommendationservice:2.1

    - name: Build and push shippingservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/shippingservice:2.1

    - name: Build and push productcatalogservice
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: iscanprint/productcatalogservice:2.1

    - name: Build and push redis-cart
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: redis:alpine3.16

    - name: Build and push admin-node
      uses: docker/build-push-action@v4
      with:
        context: ./work/admin-node
        file: Dockerfile
        push: true
        tags: iscanprint/admin-node:latest

    - name: Build and push jaeger
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: jaegertracing/all-in-one:1.34.1

    - name: Deploy with Docker Compose
      run: docker-compose -f docker-compose.yml up -d
