name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          services=("adservice" "cartservice" "checkoutservice" "currencyservice" "emailservice" "frontend" "loadgenerator" "paymentservice" "productcatalogservice" "recommendationservice" "shippingservice")
          cd 10tier/src
          for service in "${services[@]}"; do
            if [ -d "$service" ]; then
              cd "$service"
              docker build -t ghcr.io/${DOCKER_USERNAME}/${service}:latest .
              docker push ghcr.io/${DOCKER_USERNAME}/${service}:latest
              cd ..
            else
              echo "Directory $service does not exist."
            fi
          done

      - name: Run Docker Compose
        run: |
          cd mcsvc
          docker-compose -f docker-compose.yml up -d
