jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Start Minikube
        id: minikube
        uses: hiberbee/github-action-minikube@master
      - name: Get Minikube IP
        run: echo ${{ steps.minikube.outputs.ip }}
