name: Minikube Setup

on: [push]

jobs:
  setup-minikube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update and upgrade dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y apt-transport-https ca-certificates curl

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        sudo minikube start --driver=docker

    - name: Verify Minikube Status
      run: |
        minikube status

    - name: Get Cluster Info
      run: |
        kubectl cluster-info
